config/routes.rb
Produktionskort::Application.routes.draw do
  devise_for :users

  root :to => 'projects#index'

  match 'om' => 'about#index', :as => 'about', :conditions => { :method => :get }

  resources :projects do
    collection do
      get :switch
      post :switch
    end

    resources :work_processes, :shallow => true do
      resource :export, :controller => 'export', :only => [:new, :create]
    end

    namespace :byggeweb do
      resources :folders, :only => [:index, :show] do
        resources :files, :only => [:index, :show]
      end
    end
    namespace :fileshare do
      resources :folders, :only => :index
      resources :files, :only => :index
      match 'files/*key' => 'files#download'
    end
    namespace :bips do
      resources :sections, :only => [:index, :show] do
        resources :content, :only => :index
      end
    end
  end
end

app/controllers/work_processes_controller.rb
class WorkProcessesController < ApplicationController
  ATTACHMENT_KEYS = [:activity_referrals_attributes, :equipment_referrals_attributes, :material_referrals_attributes, :crew_referrals_attributes, :work_method_referrals_attributes]

  before_filter :fix_nested_attribute_structure, :only => [:create, :update]

  def index
    @project = current_user.projects.find(params[:project_id])
    @work_processes = @project.work_processes

    respond_to do |format|
      format.html
      format.xml { render :xml => @work_processes.to_xml }
    end
  end
  
  def show
    @work_process = current_user.work_processes.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml do
        render :xml => @work_process.to_xml_deep
      end
    end
  end
  
  def new
    @project = current_user.projects.find(params[:project_id])
    @work_process = @project.work_processes.build
  end
  
  def create
    @project = current_user.projects.find(params[:project_id])
    process_attachments :work_process, ATTACHMENT_KEYS, @project
    @work_process = @project.work_processes.build(params[:work_process])
    respond_to do |format|
      if @work_process.save
        flash[:notice] = "Produktionskort oprettet."
        format.html { redirect_to @work_process }
        format.xml { render :xml => @work_process.to_xml_deep }
      else
        format.html { render :action => 'new' }
        format.xml { render :xml => @work_process.errors.to_xml, :status => 400 }
      end
    end
  end
  
  def edit
    @work_process = current_user.work_processes.find(params[:id])
  end
  
  def update
    @work_process = current_user.work_processes.find(params[:id])
    process_attachments :work_process, ATTACHMENT_KEYS, @work_process.project

    respond_to do |format|
      if @work_process.update_attributes(params[:work_process])
        flash[:notice] = "Produktionskort opdateret."
        format.html { redirect_to @work_process }
        format.xml { render :xml => @work_process.to_xml_deep }
      else
        format.html { render :action => 'edit' }
        format.xml { render :xml => @work_process.errors.to_xml, :status => 400 }
      end
    end
  end
  
  def destroy
    @work_process = current_user.work_processes.find(params[:id])
    project_id = @work_process.project_id
    @work_process.destroy
    respond_to do |format|
      flash[:notice] = "Produktionskort slettet."
      format.html { redirect_to project_work_processes_url(project_id) }
      format.xml { render :nothing => true }
    end
  end
end

app/views/work_processes/_activity_referral_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => f.object.class.kinds, :include_blank => false %>
  <%= f.input :notes %>
  <%= f.input :identifier %>
  <%= attachment_fiels f %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/work_processes/_crew_referral_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => f.object.class.kinds, :include_blank => false %>
  <%= f.input :notes %>
  <%= f.input :identifier %>
  <%= attachment_fiels f %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/work_processes/_equipment_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => Equipment::KINDS, :include_blank => false %>
  <%= f.input :notes %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/work_processes/_equipment_referral_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => f.object.class.kinds, :include_blank => false %>
  <%= f.input :notes %>
  <%= f.input :identifier %>
  <%= attachment_fiels f %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/work_processes/_form.html.erb
<% sidebar [['Aktivitet',     '#', {:class => 'active tab', :rel => 'pane_activity'}],
            ['Planlægning',   '#', {:class => 'tab', :rel => 'pane_planning'}],
            ['Arbejdsmetode', '#', {:class => 'tab', :rel => 'pane_work_method'}],
            ['Materiel',      '#', {:class => 'tab', :rel => 'pane_equipment'}],
            ['Materialer',    '#', {:class => 'tab', :rel => 'pane_materials'}],
            ['Mandskab',      '#', {:class => 'tab', :rel => 'pane_men'}]], :submit => ['Gem', 'work_process_form'] %>

<%= semantic_form_for [@project, @work_process], :html => {:id => 'work_process_form', :multipart => true} do |f| %>
  <%= f.inputs :class => 'pane', :id => 'pane_activity' do %>
    <h3>Aktivitet</h3>
    <%= f.input :component_type %>
    <%= f.input :activity %>
    <%= f.input :activity_number %>
    <%= f.input :extra_work %>
    <%= f.input :value, :input_html => { :size => 5 }, :wrapper_html => { :class => 'col1' } %>
    <%= f.input :unit, :input_html => { :size => 5 }, :wrapper_html => { :class => 'col2' } %>
    <%= f.input :location %>
    <%= f.input :project_delivery_time %>
    <%= f.input :project_delivery_person %>

    <fieldset class="table_group"><legend><span>Byggepladsadresse</span></legend>
      <dl>
        <dt>Vej</dt>
        <dd><%= @work_process.project.address %></dd>
        <dt>Matrikelnr</dt>
        <dd><%= @work_process.project.title_number %></dd>
        <dt>Postnr</dt>
        <dd><%= @work_process.project.postal_code %></dd>
      </dl>
    </fieldset>

    <fieldset class="table_group"><legend><span>Andre adresser</span></legend>
      <%= f.semantic_fields_for :companies do |builder| %>
        <%= render 'company_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj virksomhed", f, :companies %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Henvisninger</span></legend>
      <%= f.semantic_fields_for :activity_referrals do |builder| %>
        <%= render 'activity_referral_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj henvisning", f, :activity_referrals %></p>
    </fieldset>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_planning' do %>
    <h3>Planlægning</h3>
    <%= f.input :main_start %>
    <%= f.input :main_end %>
    <%= f.input :preceding %>
    <%= f.input :subsequent %>
    <%= f.input :planned_start %>
    <%= f.input :planned_end %>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_work_method' do %>
    <h3>Arbejdsmetode</h3>
    <%= f.input :assembly_direction, :as => :text, :input_html => { :rows => 10 } %>

    <fieldset class="table_group"><legend><span>Krav</span></legend>
      <%= f.semantic_fields_for :requirements do |builder| %>
        <%= render 'requirement_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj krav", f, :requirements %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Udførelseskontrol</span></legend>
      <%= f.semantic_fields_for :inspections do |builder| %>
        <%= render 'inspection_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj kontrol", f, :inspections %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Værnemidler</span></legend>
      <%= f.semantic_fields_for :protections do |builder| %>
        <%= render 'protection_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj værnemiddel", f, :protections %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Henvisninger</span></legend>
      <%= f.semantic_fields_for :work_method_referrals do |builder| %>
        <%= render 'work_method_referral_fields', :f => builder %>
       <% end %>
       <p><%= link_to_add_fields "Tilføj henvisning", f, :work_method_referrals %></p>
    </fieldset>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_equipment' do %>
    <h3>Materiel</h3>
    <fieldset class="table_group"><legend><span>Henvisninger</span></legend>
      <%= f.semantic_fields_for :equipment_referrals do |builder| %>
        <%= render 'equipment_referral_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj henvisning", f, :equipment_referrals %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Process specifikt materiel</span></legend>
      <%= f.semantic_fields_for :equipment do |builder| %>
        <%= render 'equipment_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj materiel", f, :equipment %></p>
    </fieldset>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_materials' do %>
    <h3>Materialer</h3>
    <fieldset class="table_group"><legend><span>Materialepakker</span></legend>
      <%= f.semantic_fields_for :material_packages do |builder| %>
        <%= render 'material_package_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj Materialepakke", f, :material_packages %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Henvisninger</span></legend>
      <%= f.semantic_fields_for :material_referrals do |builder| %>
        <%= render 'material_referral_fields', :f => builder %>
       <% end %>
       <p><%= link_to_add_fields "Tilføj henvisning", f, :material_referrals %></p>
    </fieldset>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_men' do %>
    <h3>Mandskab</h3>
    <%= f.input :responsible %>
    <%= f.input :duration %>
    <%= f.input :piecework_rate %>
    <%= f.input :hourly_rate %>
    <%= f.input :bonus %>
    <%= f.input :incentive_deal %>
    <%= f.input :allowance %>
    <%= f.input :time_of_day %>

    <fieldset class="table_group"><legend><span>Henvisninger</span></legend>
      <%= f.semantic_fields_for :crew_referrals do |builder| %>
        <%= render 'crew_referral_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj henvisning", f, :crew_referrals %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Kompetencer</span></legend>
      <%= f.semantic_fields_for :qualifications do |builder| %>
        <%= render 'qualification_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj kompetence", f, :qualifications %></p>
    </fieldset>
  <% end %>
<% end %>

app/views/work_processes/_group_referrals.html.erb
  <% group_referrals(ref_arr).each_pair do |kind,referrals| %>
    <h3>Relevante <%= kind.to_s %><%= kind.to_s =~ /er$/ ? '' : (kind.to_s =~ /e$/ ? 'r' : 'er') %></h3>
    <table>
      <thead>
        <tr>
          <th>Tekst</th>
          <th>Henvisning</th>
          <th>Vedhæftning</th>
        </tr>
      </thead>
      <tbody>
      <% for referral in referrals do %>
        <tr class="<%= cycle("odd", "even") -%>">
          <td><%= referral.notes %></td>
          <td><%= referral.identifier %></td>
          <td><%= link_to(referral.attachment_file_name, referral.attachment.url) unless referral.attachment_file_name.blank? %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>

app/views/work_processes/_inspection_fields.html.erb
<%= f.inputs :class => "tableize inputs contains_sub_inserts" do %>
  <%= f.input :kind, :collection => Inspection::KINDS, :include_blank => false %>
  <%= f.input :method, :collection => Inspection::METHODS, :include_blank => false %>
  <%= f.input :notes %>
  <%= f.input :person %>
  <%= f.input :time %>
  <%= f.input :location %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

<h4>Dokumentation</h4>
<%= f.semantic_fields_for :documentations do |builder| %>
  <%= render 'documentation_fields', :f => builder %>
<% end %>
<p class="sub_insert"><%= link_to_add_fields "Tilføj dokumentation", f, :documentations %></p>

app/views/work_processes/_protection_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => Protection::KINDS, :include_blank => false %>
  <%= f.input :notes %>
  <%= f.input :usage %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/work_processes/_qualification_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :super_kind, :collection => Qualification::SUPER_KINDS, :include_blank => false %>
  <%= f.input :kind, :collection => Qualification::KINDS, :include_blank => false %>
  <%= f.input :notes %>
  <%= f.input :immaterial_currency %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/work_processes/_requirement_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => Requirement::KINDS, :include_blank => false %>
  <%= f.input :component %>
  <%= f.input :description %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/work_processes/_work_method_referral_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => f.object.class.kinds, :include_blank => false %>
  <%= f.input :notes %>
  <%= f.input :identifier %>
  <%= attachment_fiels f %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/work_processes/edit.html.erb
<% title 'Rediger produktionskort' %>
<% quicklinks [['Annuller', work_process_path(@work_process)]] %>

<%= render :partial => 'form' %>

app/views/work_processes/index.html.erb
<% title "Produktionskort" %>
<% quicklinks [['Opret nyt produktionskort', new_project_work_process_path(@project)]] %>

<h3>Oversigt</h3>

<% if @work_processes.blank? %>
<p>Der er p.t. ikke oprettet nogen produktionskort for denne byggesag.</p>
<p><%= link_to 'Opret et med det samme!', new_project_work_process_path(@project) %></p>
<% else %>
<table>
  <thead>
    <tr>
      <th><%= WorkProcess.human_attribute_name('component_type') %></th>
      <th><%= WorkProcess.human_attribute_name('activity') %></th>
      <th><%= WorkProcess.human_attribute_name('location') %></th>
      <th></th>
    </tr>
  </thead>
  <% for work_process in @work_processes %>
  <tbody>
    <tr class="<%= cycle("odd", "even") -%>">
      <td><%= work_process.component_type %></td>
      <td><%= work_process.activity %></td>
      <td><%= work_process.location %></td>
      <td class="action">
        <%= link_to t('navigation.show'), work_process, :class => 'view' %>
        <%= link_to t('navigation.edit'), edit_work_process_path(work_process), :class => 'edit' %>
        <%= link_to t('navigation.destroy'), work_process, :confirm => 'Er du sikker?', :method => :delete, :class => 'delete' %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
<% end %>

app/views/work_processes/show.html.erb
<% title 'Produktionskort' %>
<% quicklinks [['Download', new_work_process_export_path(@work_process)],
               ['Rediger', edit_work_process_path(@work_process)]] %>
<% sidebar [['Stamdata',      '#', {:class => 'active tab', :rel => 'pane_stemdata'}],
            ['Byggeplads',    '#', {:class => 'tab', :rel => 'pane_buildingsite'}],
            ['Planlægning',   '#', {:class => 'tab', :rel => 'pane_planning'}],
            ['Aktivitet',     '#', {:class => 'tab', :rel => 'pane_activity'}],
            ['Arbejdsmetode', '#', {:class => 'tab', :rel => 'pane_work_method'}],
            ['Materiel',      '#', {:class => 'tab', :rel => 'pane_equipment'}],
            ['Materialer',    '#', {:class => 'tab', :rel => 'pane_materials'}],
            ['Mandskab',      '#', {:class => 'tab', :rel => 'pane_men'}]] %>
<div id="left_print_col">
<div class="pane content" id="pane_stemdata">
  <h3 class="first"><%= @work_process.activity %></h3>
  <dl>
    <dt>Projekt</dt><dd><%= @work_process.project.name %></dd>
    <dt>Aktivitetsnummer</dt><dd><%= @work_process.activity_number %></dd>
    <dt>Ekstraarbejde</dt><dd><%= @work_process.extra_work ? "Ja" : "Nej" %></dd>
  </dl>

  <h3>Adresse</h3>
  <dl>
    <dt>Vej</dt><dd><%= @work_process.project.address %></dd>
    <dt>Matrikelnr</dt><dd><%= @work_process.project.title_number %></dd>
    <dt>Postnr</dt><dd><%= @work_process.project.postal_code %></dd>
  </dl>

  <h3>Personer</h3>
  <dl>
    <% for person in @work_process.project.people do %>
    <dt><%= person.kind %></dt>
    <dd><%= person.name %> - <%= person.mobile_tel %></dd>
    <% end %>
  </dl>
</div>

<div class="pane content" style="display:none" id="pane_buildingsite">
  <h3>Byggeplads</h3>
  <%= render 'group_referrals', :ref_arr => @work_process.project.site_referrals %>

  <h3>Bemærkninger</h3>
  <ul>
    <% for focus in @work_process.project.site_focuses do %>
    <li><%= focus.description %> (<%= focus.kind %>)</li>
    <% end %>
    <% for operation in @work_process.project.site_operations do %>
    <li><%= operation.description %> (<%= operation.kind %>)</li>
    <% end %>
  </ul>
</div>

<div class="pane content" style="display:none" id="pane_planning">
  <h3>Planlægning</h3>
  <dl>
    <dt>Planlagt start</dt><dd><%= @work_process.planned_start.to_s(:short) unless @work_process.planned_start.blank? %></dd>
    <dt>Planlagt slut</dt><dd><%= @work_process.planned_end.to_s(:short) unless @work_process.planned_end.blank? %></dd>
    <dt>Forudgående</dt><dd><%= @work_process.preceding %></dd>
    <dt>Efterfølgende</dt><dd><%= @work_process.subsequent %></dd>
  </dl>
  <%= render 'group_referrals', :ref_arr => @work_process.project.planning_referrals %>
</div>

<div class="pane content" style="display:none" id="pane_activity">
  <h3>Montage</h3>
  <dl>
    <dt>Aktivitet</dt><dd><%= @work_process.activity %></dd>
    <dt>Placering</dt><dd><%= @work_process.location %></dd>
    <dt>Levering senest</dt><dd><%= @work_process.project_delivery_time %></dd>
    <dt>Ansvarlig</dt><dd><%= @work_process.project_delivery_person %></dd>
    <dt><%= @work_process.unit %></dt><dd><%= @work_process.value %></dd>
  </dl>
  <%= render 'group_referrals', :ref_arr => @work_process.activity_referrals %>
</div>
</div>

<div id="right_print_col">
<div class="pane content" style="display:none" id="pane_work_method">
  <h3>Krav</h3>
  <ul>
    <% for requirement in @work_process.requirements do %>
    <li><%= requirement.kind %><%= " #{requirement.component}:" unless requirement.component.blank? %><%= " #{requirement.description}" unless requirement.description.blank? %></li>
    <% end %>
  </ul>

  <h3>Værnemidler</h3>
  <ul>
    <% for protection in @work_process.protections do %>
    <li><%= "#{protection.kind}:" %><%= " #{protection.notes}" unless protection.notes.blank? %><%= " #{protection.usage}" unless protection.usage.blank? %></li>
    <% end %>
  </ul>

  <%= render 'group_referrals', :ref_arr => @work_process.work_method_referrals %>
</div>

<div class="pane content" style="display:none" id="pane_equipment">
  <h3>Materiel</h3>
  <%= render 'group_referrals', :ref_arr => @work_process.equipment_referrals %>

  <h3>Process specifikt materiel</h3>
  <ul>
    <% for equipment in @work_process.equipment do %>
    <li><%= "#{equipment.kind}:" %><%= " #{equipment.notes}" unless equipment.notes.blank? %></li>
    <% end %>
  </ul>
</div>

<div class="pane content" style="display:none" id="pane_materials">
  <h3>Materialer</h3>
  <% for material_package in @work_process.material_packages do %>
    <h3>Materialepakke, unitnr.: <%= material_package.unit_number %> (<%= material_package.supplier %>)</h3>
    <table>
      <thead>
        <tr>
          <th>Type</th>
          <th>Antal</th>
          <th>Vægt</th>
          <th>Mål</th>
          <th>Længde</th>
        </tr>
      </thead>
      <tbody>
        <% for material in material_package.materials do %>
        <tr class="<%= cycle("odd", "even") -%>"><td><%= material.kind %></td><td class="right"><%= material.count %></td><td class="right"><%= material.weight %></td><td class="right"><%= material.measures %> <%= material.unit %></td><td class="right"><%= material.lengths %> <%= material.unit %></td></tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <%= render 'group_referrals', :ref_arr => @work_process.material_referrals %>
</div>

<div class="pane content" style="display:none" id="pane_men">
  <h3>Mandskab</h3>
  <dl>
    <% unless @work_process.responsible.blank? %><dt>Ansvarlig</dt><dd><%= @work_process.responsible %></dd><% end %>
    <% unless @work_process.duration.blank? %><dt>Varighed (timer)</dt><dd><%= @work_process.duration %></dd><% end %>
    <% unless @work_process.piecework_rate.blank? %><dt>Akkord</dt><dd><%= @work_process.piecework_rate %></dd><% end %>
    <% unless @work_process.hourly_rate.blank? %><dt>Timeløn</dt><dd><%= @work_process.hourly_rate %></dd><% end %>
    <dt>Bonus</dt><dd><%= @work_process.bonus ? "Ja" : "Nej" %></dd>
    <dt>Incitamentaftale</dt><dd><%= @work_process.incentive_deal ? "Ja" : "Nej" %></dd>
    <% unless @work_process.allowance.blank? %><dt>Godtgørelse</dt><dd><%= @work_process.allowance %></dd><% end %>
    <% unless @work_process.time_of_day.blank? %><dt>Tid på dagen</dt><dd><%= @work_process.time_of_day %></dd><% end %>
  </dl>
  <%= render 'group_referrals', :ref_arr => @work_process.crew_referrals %>

  <h3>Kompetencer</h3>
  <ul>
    <% for qualification in @work_process.qualifications do %>
    <li><%= "#{qualification.kind}:" %><%= " #{qualification.notes}" unless qualification.notes.blank? %><%= " (Immatriel møntfod #{qualification.immaterial_currency})" unless qualification.immaterial_currency.blank? %></li>
    <% end %>
  </ul>
</div>
</div>