config/routes.rb
Produktionskort::Application.routes.draw do
  devise_for :users

  root :to => 'projects#index'

  match 'om' => 'about#index', :as => 'about', :conditions => { :method => :get }

  resources :projects do
    collection do
      get :switch
      post :switch
    end

    resources :work_processes, :shallow => true do
      resource :export, :controller => 'export', :only => [:new, :create]
    end

    namespace :byggeweb do
      resources :folders, :only => [:index, :show] do
        resources :files, :only => [:index, :show]
      end
    end
    namespace :fileshare do
      resources :folders, :only => :index
      resources :files, :only => :index
      match 'files/*key' => 'files#download'
    end
    namespace :bips do
      resources :sections, :only => [:index, :show] do
        resources :content, :only => :index
      end
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :work_processes, :dependent => :destroy
  has_many :approvals, :dependent => :destroy
  has_many :attentions, :dependent => :destroy
  has_many :companies, :dependent => :destroy
  has_many :equipment, :dependent => :destroy
  has_many :meetings, :dependent => :destroy
  has_many :people, :dependent => :destroy
  has_many :site_focuses, :dependent => :destroy
  has_many :site_operations, :dependent => :destroy
  has_many :site_responsibilities, :dependent => :destroy
  has_many :planning_referrals, :dependent => :destroy
  has_many :site_referrals, :dependent => :destroy

  belongs_to :user

  accepts_nested_attributes_for :work_processes,
                                :approvals,
                                :attentions,
                                :companies,
                                :equipment,
                                :meetings,
                                :people,
                                :site_focuses,
                                :site_operations,
                                :site_responsibilities,
                                :planning_referrals,
                                :site_referrals, :allow_destroy => true

  validates_presence_of :name

  def fileshare_prefix
    if self[:fileshare_prefix].blank?
      self[:fileshare_prefix] = SecureRandom.hex
    end
    self[:fileshare_prefix]
  end

  def byggeweb
    return if [byggeweb_username, byggeweb_password].grep(/./).empty?
    @byggeweb ||= Byggeweb.new byggeweb_username, byggeweb_password, byggeweb_project
  end

  def fileshare
    @fileshare ||= Fileshare::Base.new(fileshare_prefix)
  end

  def bips_root_sections
    [
      jsonize_section("Foo"),
      jsonize_section("Bar"),
      jsonize_section("Test")
    ]
  end

  def bips_section(id)
    sections = ["Lorem Ipsum", "Overskrift A", "Test", "Punkt 1", "Endnu et punkt", "Test 123"]
    sections.map! { |name| jsonize_section name }
    sections.reject! { rand(2) == 0 }
    sections.shuffle
  end

  def bips_content(section_id)
    headlines = ["Overskrit A", "Overskrit B", "Overskrit C"]
    content = [
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nulla justo ipsum, rutrum a, consectetuer ac, malesuada vel, lacus. Vestibulum eu ligula. Vestibulum sed enim. Donec metus ante, tempor et, sollicitudin sed, consectetuer a, orci. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin volutpat. Nullam risus. Nam dignissim dolor nec urna. Quisque massa lacus, aliquet vitae, congue sed, consectetuer pharetra, ligula. In hac habitasse platea dictumst. Integer commodo sagittis felis. Vivamus et ipsum. Morbi sodales, purus hendrerit tincidunt aliquam, eros purus bibendum mi, id interdum wisi nunc sit amet tortor. Sed pharetra. Etiam laoreet arcu ut enim. In et eros. Sed vel ligula nec quam venenatis dictum. Praesent risus.",
      "Nullam justo magna, dignissim ut, ultricies eget, mollis sit amet, enim. Nulla consectetuer, dui id tempus varius, nunc libero tincidunt orci, nec fringilla eros eros in leo. Nullam vulputate tellus vel est. Donec vel urna vel metus volutpat egestas. In commodo, augue vitae pulvinar blandit, neque elit auctor metus, in bibendum magna tortor et diam. Nulla sapien. Donec ultrices felis a dui. Nam a risus in velit porttitor pretium. Quisque pharetra mi nec nulla. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
      "Mauris at mauris. Phasellus justo. Ut urna. Quisque pede dui, dignissim a, ullamcorper et, bibendum vitae, sapien. Proin ut diam. Aenean purus. Ut ante. Mauris consectetuer lectus at est. Nam id leo. Maecenas at eros. In lectus pede, porttitor eu, imperdiet sed, malesuada sed, dui. Suspendisse venenatis, justo nec dapibus bibendum, odio eros ultricies nisl, in porta quam libero vitae erat. Aenean imperdiet tempus elit. Phasellus pellentesque mauris non velit facilisis egestas. Proin ultrices, dolor eu rutrum ullamcorper, velit odio bibendum turpis, in accumsan massa elit nec nulla. Vivamus lacus. Proin accumsan. Nullam magna.",
      "Morbi tellus tortor, adipiscing vel, rutrum quis, tempus vitae, purus. Etiam lorem eros, fermentum vitae, euismod ut, varius porta, lorem. In quis diam. Cras scelerisque. Cras pharetra massa id ligula. Ut tortor. Aenean ipsum nunc, rhoncus vel, sagittis non, luctus sed, est. Integer condimentum. Ut nonummy, orci eget iaculis semper, sem sapien mollis ante, ac hendrerit lacus lacus eget tellus. Phasellus scelerisque tempor sapien. Nulla facilisi. Curabitur sagittis pretium lectus. Sed a ante. Aliquam erat volutpat. Quisque hendrerit sem eu odio. Duis rhoncus. Vestibulum scelerisque tortor ut nulla. Mauris risus massa, nonummy in, tincidunt eget, imperdiet eget, massa. Pellentesque at ligula.",
      "Nunc lobortis ligula a wisi lobortis lacinia. Cras ut diam. Nam interdum, erat id venenatis convallis, neque elit viverra nisl, in ultrices est odio non arcu. Fusce interdum consequat massa. Mauris interdum. Nunc sagittis ultrices justo. Praesent sagittis. Praesent quis neque non mi imperdiet dictum. Aliquam dictum luctus neque. Morbi lobortis. Fusce consequat fermentum nisl. Praesent vestibulum. Proin pretium tempus elit."
    ]
    content.map! { |content| { :headline => headlines[rand(3)], :body => content, :id => rand(1024) } }
    content[rand(5)]
  end

  # when generating dummy nodes, you can leave the ID blank to get a random ID
  def jsonize_section(name, id = nil, open = false, children = [])
    {
      :data => {
        :title => name,
        :attr => { :class => 'tree-node' }
      },
      :attr => { :rel => id || rand(1024) },
      :state => (open ? 'open' : 'closed'),
      :children => children
    }
  end

  def to_xml(options = {}, &block)
    options[:except] ||= []
    options[:except].concat([:byggeweb_project, :byggeweb_username, :byggeweb_password]).uniq!
    super
  end

  def to_json(options = {})
    options[:except] ||= []
    options[:except].concat([:byggeweb_project, :byggeweb_username, :byggeweb_password]).uniq!
    super
  end

  def to_xml_deep
    to_xml(
      :include => {
        :approvals => {},
        :attentions => {},
        :companies => {},
        :equipment => {},
        :meetings => {},
        :people => {},
        :site_focuses => {},
        :site_operations => {},
        :site_responsibilities => {},
        :planning_referrals => {},
        :site_referrals => {}
      }
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  ATTACHMENT_KEYS = [:planning_referrals_attributes, :site_referrals_attributes, :approvals_attributes]

  def index
    @projects = current_user.projects.all

    respond_to do |format|
      format.html
      format.xml { render :xml => @projects.to_xml }
    end
  end

  def new
    @project = Project.new
    @project.work_processes.build
  end
  
  def create
    process_attachments :project, ATTACHMENT_KEYS
    @project = current_user.projects.build(params[:project])

    respond_to do |format|
      if @project.save
        flash[:notice] = "Byggesag oprettet."
        format.html { redirect_to :action => 'index' }
        format.xml { render :xml => @project.to_xml }
      else
        format.html { render :action => 'new' }
        format.xml { render :xml => @project.errors.to_xml, :status => 400 }
      end
    end
  end

  def show
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      format.html { render :nothing => true, :status => 404 }
      format.xml do
        render :xml => @project.to_xml_deep
      end
    end
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end
  
  def update
    @project = current_user.projects.find(params[:id])
    process_attachments :project, ATTACHMENT_KEYS, @project

    respond_to do |format|
      if @project.update_attributes(params[:project])
        flash[:notice] = "Stamdata for byggesag opdateret."
        format.html { redirect_to :action => 'index' }
        format.xml { render :xml => @project.to_xml }
      else
        format.html { render :action => 'edit' }
        format.xml { render :xml => @project.errors.to_xml, :status => 400 }
      end
    end
  end
  
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy
    respond_to do |format|
      flash[:notice] = "Byggesag slettet."
      format.html { redirect_to projects_url }
      format.xml { render :nothing => true }
    end
  end

  def switch
    if params[:id] == 'new'
      redirect_to :action => 'new'
    else
      project = current_user.projects.find(params[:id])
      cookies['active_project'] = project.id
      redirect_to project_work_processes_path(project)
    end
  end
end

app/views/projects/_approval_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => Approval::KINDS, :include_blank => false %>
  <%= f.input :description %>
  <%= f.input :time %>
  <%= attachment_fiels f %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/projects/_attention_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => Attention::KINDS, :include_blank => false %>
  <%= f.input :description %>
  <%= f.input :time %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/projects/_equipment_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => Equipment::KINDS, :include_blank => false %>
  <%= f.input :notes %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/projects/_external_systems_pane.html.erb
<%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_external_systems' do %>
  <h3>Eksterne systemer</h3>

  <%= f.inputs "Filbibliotek", :class => "table_group" do %>
    <h4>S3 Folder</h4>
    <%= @project.fileshare.prefix %>
  <% end %>

  <%= f.inputs "Byggeweb", :class => "table_group" do %>
    <%= f.input :byggeweb_username, :label => 'Brugernavn' %>
    <%= f.input :byggeweb_password, :label => 'Password', :as => :password %>
    <% if @project.byggeweb.try(:logged_in?) %>
    <%= f.input :byggeweb_project, :label => 'Projekt', :as => :select, :collection => @project.byggeweb.projects %>
    <% else %>
    <li class="string optional" id="project_byggeweb_project_input">
      <label for="project_byggeweb_project">Projekt</label>
      <p class="inline-hints">Kan ikke logge ind i Byggeweb (udfyld venligst korrekte bruger-oplysninger oven for)</p>
    </li>
    <% end %>
  <% end %>
<% end %>

app/views/projects/_meeting_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => Meeting::KINDS, :include_blank => false %>
  <%= f.input :time %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/projects/_person_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => Person::KINDS, :include_blank => false %>
  <%= f.input :name %>
  <%= f.input :street_address %>
  <%= f.input :extended_address %>
  <%= f.input :postal_code, :input_html => { :size => 5 }, :wrapper_html => { :class => 'col1' } %>
  <%= f.input :city, :input_html => { :size => 30 }, :wrapper_html => { :class => 'col2' } %>
  <%= f.input :tel %>
  <%= f.input :direct_tel %>
  <%= f.input :mobile_tel %>
  <%= f.input :email %>
  <%= f.input :url %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/projects/_planning_referral_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => f.object.class.kinds, :include_blank => false %>
  <%= f.input :notes %>
  <%= f.input :identifier %>
  <%= attachment_fiels f %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/projects/_site_focus_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => SiteFocus::KINDS, :include_blank => false %>
  <%= f.input :description %>
  <%= f.input :last_inspection %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/projects/_site_operation_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => SiteOperation::KINDS, :include_blank => false %>
  <%= f.input :description %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/projects/_site_referral_fields.html.erb
<%= f.inputs :class => "tableize inputs" do %>
  <%= f.input :kind, :collection => f.object.class.kinds, :include_blank => false %>
  <%= f.input :notes %>
  <%= f.input :identifier %>
  <%= attachment_fiels f %>
  <%= link_to_remove_fields "Slet", f %>
<% end %>

app/views/projects/_stemdata_pane.html.erb
<%= f.inputs :class => 'pane', :id => 'pane_stemdata' do %>
  <h3>Stamdata</h3>
  <%= f.inputs :name, :address, :title_number, :postal_code, :apv_location, :health_safety_decided_by_owner,
               :health_safety_decided_by_contractor, :health_safety_plan, :health_safety_plan_location %>
<% end %>

app/views/projects/edit.html.erb
<% title @project.name %>
<% quicklinks [[t('navigation.destroy'), @project, {:confirm => 'Er du sikker?', :method => :delete}],
               ['Annuller', projects_path]] %>

<% sidebar [['Stamdata',          '#', {:class => 'active tab', :rel => 'pane_stemdata'}],
            ['Eksterne systemer', '#', {:class => 'tab', :rel => 'pane_external_systems'}],
            ['Personer',          '#', {:class => 'tab', :rel => 'pane_people'}],
            ['Møder',             '#', {:class => 'tab', :rel => 'pane_meetings'}],
            ['Godkendelser',      '#', {:class => 'tab', :rel => 'pane_approvals'}],
            ['Hensyn',            '#', {:class => 'tab', :rel => 'pane_attentions'}],
            ['Planlægning',       '#', {:class => 'tab', :rel => 'pane_planning'}],
            ['Byggeplads',        '#', {:class => 'tab', :rel => 'pane_buildingsite'}]], :submit => ['Gem', 'project_form'] %>

<%= semantic_form_for @project, :html => {:id => 'project_form', :multipart => true} do |f| %>
  <%= render 'stemdata_pane', :f => f %>
  <%= render 'external_systems_pane', :f => f %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_people' do %>
    <h3>Personer</h3>

    <fieldset class="table_group">
      <%= f.semantic_fields_for :people do |builder| %>
        <%= render 'person_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj person", f, :people %></p>
    </fieldset>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_meetings' do %>
    <h3>Møder</h3>

    <fieldset class="table_group">
      <%= f.semantic_fields_for :meetings do |builder| %>
        <%= render 'meeting_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj møde", f, :meetings %></p>
    </fieldset>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_approvals' do %>
    <h3>Godkendelser</h3>

    <fieldset class="table_group">
      <%= f.semantic_fields_for :approvals do |builder| %>
        <%= render 'approval_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj godkendelse", f, :approvals %></p>
    </fieldset>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_attentions' do %>
    <h3>Hensyn</h3>

    <fieldset class="table_group">
      <%= f.semantic_fields_for :attentions do |builder| %>
        <%= render 'attention_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj hensyn", f, :attentions %></p>
    </fieldset>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_planning' do %>
    <h3>Planlægning</h3>

    <fieldset class="table_group">
      <%= f.semantic_fields_for :planning_referrals do |builder| %>
        <%= render 'planning_referral_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj henvisning", f, :planning_referrals %></p>
    </fieldset>
  <% end %>

  <%= f.inputs :class => 'pane', :style => 'display:none', :id => 'pane_buildingsite' do %>
    <h3>Byggeplads</h3>

    <fieldset class="table_group"><legend><span>Henvisninger</span></legend>
      <%= f.semantic_fields_for :site_referrals do |builder| %>
        <%= render 'site_referral_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj henvisning", f, :site_referrals %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Byggepladsfokus</span></legend>
      <%= f.semantic_fields_for :site_focuses do |builder| %>
        <%= render 'site_focus_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj fokusområde", f, :site_focuses %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Byggepladsdrift</span></legend>
      <%= f.semantic_fields_for :site_operations do |builder| %>
        <%= render 'site_operation_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj driftsinformation", f, :site_operations %></p>
    </fieldset>

    <fieldset class="table_group"><legend><span>Materiel</span></legend>
      <%= f.semantic_fields_for :equipment do |builder| %>
        <%= render 'equipment_fields', :f => builder %>
      <% end %>
      <p><%= link_to_add_fields "Tilføj materiel", f, :equipment %></p>
    </fieldset>
  <% end %>
<% end %>

app/views/projects/index.html.erb
<% title 'Byggesager' %>

<h3>Oversigt</h3>

<% if @projects.empty? %>
<p>Der er p.t. ikke oprettet nogen byggesager.</p>
<p><%= link_to 'Opret en med det samme!', new_project_path %></p>
<% else %>
<table>
  <thead>
    <tr>
      <th><%= Project.human_attribute_name('name') %></th>
      <th><%= Project.human_attribute_name('address') %></th>
      <th><%= Project.human_attribute_name('title_number') %></th>
      <th><%= Project.human_attribute_name('postal_code') %></th>
      <th></th>
    </tr>
  </thead>
  <% for project in @projects %>
  <tbody>
    <tr class="<%= cycle("odd", "even") -%>">
      <td><%= link_to project.name, switch_projects_path(:id => project.id) %></td>
      <td><%= project.address %></td>
      <td><%= project.title_number %></td>
      <td><%= project.postal_code %></td>
      <td class="action" style="white-space:nowrap">
        <%= link_to t('navigation.edit'), edit_project_path(project), :class => 'edit' %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
<% end %>

app/views/projects/new.html.erb
<% title 'Opret byggesag' %>
<% quicklinks [['Annuller', projects_path]] %>

<% sidebar [['Stamdata',          '#', {:class => 'active tab', :rel => 'pane_stemdata'}],
            ['Eksterne systemer', '#', {:class => 'tab', :rel => 'pane_external_systems'}]], :submit => ['Gem', 'project_form'] %>

<%= semantic_form_for @project, :html => {:id => 'project_form', :multipart => true} do |f| %>
  <%= render 'stemdata_pane', :f => f %>
  <%= render 'external_systems_pane', :f => f %>
<% end %>