config/routes.rb
Produktionskort::Application.routes.draw do
  devise_for :users

  root :to => 'projects#index'

  match 'om' => 'about#index', :as => 'about', :conditions => { :method => :get }

  resources :projects do
    collection do
      get :switch
      post :switch
    end

    resources :work_processes, :shallow => true do
      resource :export, :controller => 'export', :only => [:new, :create]
    end

    namespace :byggeweb do
      resources :folders, :only => [:index, :show] do
        resources :files, :only => [:index, :show]
      end
    end
    namespace :fileshare do
      resources :folders, :only => :index
      resources :files, :only => :index
      match 'files/*key' => 'files#download'
    end
    namespace :bips do
      resources :sections, :only => [:index, :show] do
        resources :content, :only => :index
      end
    end
  end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title)
    content_for(:title, page_title.to_s)
  end

  def quicklinks(links)
    quicklinks = links.reverse.map do |link|
      name, path, options = link
      content_tag :li, link_to(name, path, options)
    end.join

    unless links.empty?
      content_for(:quicklinks) { content_tag :ul, quicklinks.html_safe, :id => 'quicklinks' }
    end
  end

  def sidebar(links, sidebar_options = {})
    sidebar = links.map do |link|
      name, path, options = link
      options ||= {}
      options[:class] = current_page?(path) ? [options[:class], 'active'].compact.join(' ') : options[:class]
      content_tag :li, link_to(name, path, options)
    end.join

    unless links.empty?
      sidebar = content_tag :ul, sidebar.html_safe, :class => 'sideNav'
    end

    if sidebar_options.include?(:submit)
      sidebar += content_tag :button, sidebar_options[:submit][0], :id => 'form_submitter', :rel => sidebar_options[:submit][1]
    end

    content_for(:sidebar, sidebar)
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Produktionskort" %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <%= stylesheet_link_tag :application %>
  <%= stylesheet_link_tag 'print_work_process', :media => 'print' %>
  <!--[if IE 6]>
  <%= stylesheet_link_tag 'ie6', :media => 'screen' %>
  <![endif]-->
  <!--[if IE 7]>
  <%= stylesheet_link_tag 'ie7', :media => 'screen' %>
  <![endif]-->
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
  <%= yield :head %>
</head>
<body>
  <div id="wrapper">
    <h1><a href="/"><span>Produktionskort</span></a></h1>
    <div id="user_nav">
      <% if user_signed_in? %>
        Logget ind som <%= link_to current_user.email, edit_user_registration_path %>. Ikke dig?
        <%= link_to "Log ud", destroy_user_session_path %>
      <% else %>
        <%= link_to "Opret ny bruger", new_user_registration_path %> | <%= link_to "Log ind", new_user_session_path %>
      <% end %>
    </div>
    <div id="active_project_name"><%= link_to(current_project.name, edit_project_path(current_project)) if current_project && !current_project.new_record? %></div>

    <ul id="mainNav">
      <li><%= link_to 'Byggesager', root_path, :class => (current_page?('/') ? 'active' : nil) %></li>
      <% if current_project && !current_project.new_record? %>
      <li><%= link_to 'Produktionskort', project_work_processes_path(current_project), :class => (current_page?(about_path) || current_page?('/') ? nil : 'active') %></li>
      <% end %>
      <li><%= link_to 'Om denne applikation', about_path, :class => (current_page?(about_path) ? 'active' : nil) %></li>
      <li class="project">
        <span>
          <%= form_tag switch_projects_path, :method => :post do |f| %>
            <label for="id">Skift byggesag:</label>
            <select name="id" id="switch_project">
              <option value=""></option>
              <%= options_for_select current_user.projects.all.map { |p| [p.name, p.id] } if current_user %>
              <option value="new">Opret ny...</option>
            </select>
          <% end %>
        </span>
      </li>
    </ul>

    <div id="containerHolder">
      <div id="container">
        <h2><%= yield :title %></h2>
        <%= yield :quicklinks %>

        <div id="sidebar">
          <%= yield :sidebar %>
        </div>

        <div id="main">
          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          <% end %>
          <%= yield %>
        </div>
        <div class="clear"></div>
      </div>
    </div>
    <p id="footer">
      Udviklet i samarbejde med
      <a href="http://www.3dbyggeri.dk">3dbyggeri danmark</a>,
      <a href="http://www.codegroup.dk">CodeGroup</a>,
      <a href="http://www.eg.dk">EG</a>,
      <a href="http://www.jakon.dk">JAKON</a> og
      <a href="http://www.linkslabs.com">LinKS Advice</a>
      <span class="right">
        <a href="https://github.com/3dbyggeri/produktionskort">Kildekode og information</a>
      </span>
    </p>
  </div>
</body>
</html>